import { generateCatalogMetadataForCourse, insertCourseAndGenerateTags } from '@/lib/server/course-catalog';
import type { SceneOutline } from '@/lib/types/generation';
import type { Stage } from '@/lib/types/stage';

export interface InsertCourseAndGenerateTagsParams {
  stage: Stage;
  outlines: SceneOutline[];
  requirement: string;
}

export interface GenerateCatalogMetadataParams {
  courseId: string;
  courseName: string;
  language: string;
  sceneTitles: string[];
}

/**
 * Upserts a course generated by the classroom pipeline into the catalog
 * and generates AI metadata + classification tags.
 */
export async function insertCourseAndGenerateTagsActivity(
  params: InsertCourseAndGenerateTagsParams,
): Promise<void> {
  const { stage, outlines, requirement } = params;
  const { resolveModel } = await import('@/lib/server/resolve-model');

  const { model } = resolveModel({});

  await insertCourseAndGenerateTags(stage, outlines, requirement, model);
}

/**
 * Generates catalog metadata for a course that was uploaded from the client
 * (generation-preview flow).
 */
export async function generateCatalogMetadataForCourseActivity(
  params: GenerateCatalogMetadataParams,
): Promise<void> {
  await generateCatalogMetadataForCourse(params);
}
